---
abstract: 'Pluggable benchmarker to cross-compare template systems.'
author:
  - 'Sam Graham <libtemplate-benchmark-perl@illusori.co.uk>'
build_requires:
  Config: 0
  Cwd: 0
  File::Spec: 0
  FindBin: 0
  Module::Build: 0.07
  Test::Command: 0.08
  Test::More: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 0
generated_by: 'Module::Build version 0.3601'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Benchmark
provides:
  Template::Benchmark:
    file: lib/Template/Benchmark.pm
    version: 0.99_06
  Template::Benchmark::Engine:
    file: lib/Template/Benchmark/Engine.pm
    version: 0.99_06
  Template::Benchmark::Engines::HTMLTemplate:
    file: lib/Template/Benchmark/Engines/HTMLTemplate.pm
    version: 0.99_06
  Template::Benchmark::Engines::HTMLTemplateCompiled:
    file: lib/Template/Benchmark/Engines/HTMLTemplateCompiled.pm
    version: 0.99_06
  Template::Benchmark::Engines::HTMLTemplateExpr:
    file: lib/Template/Benchmark/Engines/HTMLTemplateExpr.pm
    version: 0.99_06
  Template::Benchmark::Engines::HTMLTemplateJIT:
    file: lib/Template/Benchmark/Engines/HTMLTemplateJIT.pm
    version: 0.99_06
  Template::Benchmark::Engines::HTMLTemplatePro:
    file: lib/Template/Benchmark/Engines/HTMLTemplatePro.pm
    version: 0.99_06
  Template::Benchmark::Engines::MojoTemplate:
    file: lib/Template/Benchmark/Engines/MojoTemplate.pm
    version: 0.99_06
  Template::Benchmark::Engines::TemplateAlloyHT:
    file: lib/Template/Benchmark/Engines/TemplateAlloyHT.pm
    version: 0.99_06
  Template::Benchmark::Engines::TemplateAlloyTT:
    file: lib/Template/Benchmark/Engines/TemplateAlloyTT.pm
    version: 0.99_06
  Template::Benchmark::Engines::TemplateSandbox:
    file: lib/Template/Benchmark/Engines/TemplateSandbox.pm
    version: 0.99_06
  Template::Benchmark::Engines::TemplateToolkit:
    file: lib/Template/Benchmark/Engines/TemplateToolkit.pm
    version: 0.99_06
  Template::Benchmark::Engines::TextMicroMasonHM:
    file: lib/Template/Benchmark/Engines/TextMicroMasonHM.pm
    version: 0.99_06
  Template::Benchmark::Engines::TextMicroMasonTeTe:
    file: lib/Template/Benchmark/Engines/TextMicroMasonTeTe.pm
    version: 0.99_06
  Template::Benchmark::Engines::TextMicroTemplate:
    file: lib/Template/Benchmark/Engines/TextMicroTemplate.pm
    version: 0.99_06
  Template::Benchmark::Engines::TextTemplate:
    file: lib/Template/Benchmark/Engines/TextTemplate.pm
    version: 0.99_06
  Template::Benchmark::Engines::TextTmpl:
    file: lib/Template/Benchmark/Engines/TextTmpl.pm
    version: 0.99_06
requires:
  Benchmark: 0
  File::Path: 0
  File::Spec: 0
  FindBin: 0
  Getopt::Long: 0
  IO::File: 0
  Module::Pluggable: 0
  POSIX: 0
  Pod::Usage: 0
  Text::Wrap: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.99_06
